#不要直接编辑这个文件。可以编辑 'docker-compose.override.yaml' 文件。
#参考 `docker-compose.override.yaml.example' 文件获取一些示例配置。

name: aipyq

services:
  api:
    container_name: AIpyq
    ports:
      - "${API_PORT:-3080}:3080"
    depends_on:
      - rag_api
    image: ${DOCKER_REGISTRY:-ghcr.io}/${DOCKER_REGISTRY_USER:-your-username}/${IMAGE_PREFIX:-aipyq}:${IMAGE_TAG:-latest}
    restart: always
    user: "${UID}:${GID}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST=0.0.0.0
      - PORT=3080
      - DOMAIN_CLIENT=http://localhost:${API_PORT:-3080}
      - DOMAIN_SERVER=http://localhost:${API_PORT:-3080}
      - MONGO_URI=mongodb://host.docker.internal:${MONGO_PORT:-27017}/Aipyq
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
      - AIPYQ_LOG_DIR=/app/api/logs



      # 旧版本兼容，等镜像创建好后删除
      - LIBRECHAT_LOG_DIR=/app/api/logs
    
    
    
    
    
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs
      - ./logs:/app/logs
      # 挂载本地构建的静态资源（如果存在）
      # 取消下面的注释以使用本地构建的 dist 文件夹覆盖镜像中的静态资源
      # ./client/dist:/app/client/dist
      # ./client/public/assets:/app/client/public/assets
      # ./client/public/fonts:/app/client/public/fonts
  mongodb:
    container_name: PYQ-MongoDB
    image: mongo
    restart: always
    user: "${UID}:${GID}"
    ports:
    - "${MONGO_PORT:-27017}:27017" 
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
  meilisearch:
    container_name: PYQ-Meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always
    user: "${UID}:${GID}"
    ports:
      - "${MEILI_PORT:-7700}:7700"
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - ./meili_data_v1.12:/meili_data
  vectordb:
    container_name: vectorDB
    image: pgvector/pgvector:0.8.0-pg15-trixie
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data
  rag_api:
    container_name: Rag_api
    image: ${DOCKER_REGISTRY:-ghcr.io}/${DOCKER_REGISTRY_USER:-your-username}/${IMAGE_PREFIX:-aipyq}-rag-api:${IMAGE_TAG:-latest}
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    restart: always
    depends_on:
      - vectordb
    env_file:
      - .env

volumes:
  pgdata2:
